spring:
  h2:
    console:
      enabled: true
  datasource:
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS testdb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
    url: jdbc:postgresql://*****:5432/*********?prepareThreshold=0&preparedStatementCacheQueries=0
    username: *********
    password: **********
    testOnBorrow: true
    validationQuery: SELECT 1
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: false
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml